pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        ECR_REPO = "125903111220.dkr.ecr.us-east-1.amazonaws.com/madhu-app"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'sudo docker build -t madhu-app .'
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ECR_REPO
                '''
            }
        }

        stage('Tag Image') {
            steps {
                sh 'docker tag madhu-app:latest $ECR_REPO:latest'
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push $ECR_REPO:latest'
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }
    }
}
